---
permalink: administration/reference_snap_creator_cli_commands_for_workflow_actions.html
sidebar: sidebar
keywords: command-line, interface, cli, snap, creator, workflow, command, backup, copy
summary: 'You can use command-line interface \(CLI\) commands to perform various Snap Creator workflow actions that are based on the graphical user interface \(GUI\).'
---
= Snap Creator CLI commands for workflow actions
:icons: font
:imagesdir: ../media/

[.lead]
You can use command-line interface (CLI) commands to perform various Snap Creator workflow actions that are based on the graphical user interface (GUI).

The following table provides the CLI commands for performing Snap Creator GUI-based workflow actions:

[options="header"]
|===
| Workflow area| Action/description| Command and associated parameters
a|
Backups
a|
Create a backup copy. Performs a backup operation based on the configuration file associated with the profile.

a|

----

                  snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action backup
--policy Policy
--verbose
----

a|
Create an Open Systems SnapVault backup.Performs a backup operation using Open Systems SnapVault. This requires Snap Creator Agent. Snap Creator Server communicates with Snap Creator Agent and performs a SnapVault update. No primary backup copy is made.

a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action ossv
--policy Policy
--verbose
----

a|
Backups (contd...)
a|
Delete a backup copy (manually).Manually deletes an existing backup. This operation is menu-driven.

a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action backupDel
--policy Policy
--verbose
----

a|
Delete a backup copy (automatically).
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action backupDel
--policy Policy
--verbose
--nonInteractive
--cntName controller
--volName volume
--backupName name
----

a|
List backup copies.Lists the Snap Creator backup copies on the primary and secondary storage systems.

a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action backupList
--policy Policy
--verbose
----

a|
Mount a backup copy. Performs the mount operation on an existing backup. Creates a volume clone based on the backup, and enables the mounting of the clone through Snap Creator Agent using the MOUNT_CMD command.

a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action mount
--backupName name
--verbose
----

a|
Backups (contd...)
a|
Unmount a backup copy.Performs the unmount operation on an existing backup. Deletes a volume clone based on the backup, and enables the unmounting of the clone through Snap Creator Agent using the UMOUNT_CMDs command.

a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action umount
--backupName name
--verbose
----

a|
Backup types
a|
Create a new backup type.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action backupTypeAdd
--backupTypeName name
--verbose
----

a|
Update an existing backup type.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action backupTypeUpdate
--backupTypeId 1
--backupTypeName name
--verbose
----

a|
Delete an existing backup type.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action backupTypeDelete
--backupTypeId 1

--verbose
----

a|
List the backup types.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action backupTypeList
--verbose
----

a|
Clones
a|
Clone a LUN.Backs up the primary storage system and then clones the backup using a LUN clone. The volume mapping of igroups is also handled. This requires a SAN or iSAN environment.

a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action cloneLun
--policy Policy
--verbose
----

a|
Clone a volume.Backs up the primary storage system and then clones the backup using a volume clone. The volume mapping of igroups, NFS, or CIFS is also handled. This requires a SAN, iSAN, or NAS environment.

a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action cloneVol
--policy Policy
--verbose
----

a|
Delete a clone.Performs a clone deletion operation based on the specified retention policy. Only one copy of the LUN clone is retained. Volume clones have policy-associated usage.

a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action cloneDel
--policy Policy
--verbose
----

a|
List Snap Creator clones.Lists the Snap Creator volume clones for the given configuration.

a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action cloneList
--verbose
----

a|
List Snap Creator volumes.Lists the Snap Creator volumes for the specified configuration on the primary storage system.

a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action volumeList
--verbose
----

a|
Configuration files
a|
Import a configuration.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action configImport
--importFile file_path
--verbose
----

a|
Export a configuration.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action configExport
--exportFile file_path
--verbose
----

a|
Import a global configuration file.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action globalImport
--importFile file_path
--verbose
----

a|
Export a global configuration file.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action globalExport
--ExportFile file_path
--verbose
----

a|
Delete a global configuration file from the repository.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action globalDelete
--verbose
----

a|
Configuration files (contd...)
a|
Import a global configuration file for a particular profile to the repository.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action profileglobalImport
--importFile file_path
--verbose
----

a|
Export a global configuration file for a particular profile from the repository.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action profileglobalExport
--exportFile file_path
--verbose
----

a|
Delete a global configuration for a particular profile from the repository.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action profileglobalDelete
--verbose
----

a|
Upgrade older configuration files in a profile. Adds newly introduced parameters to older configuration files. Before executing this command, all old configuration files must be copied to the scServer/engine/configs folder along with the profile folder.

a|

----
snapcreator
--server IP
--port port
--user userid
--passwd password
--upgradeConfigs
--profile profile_name
--verbose
----

a|
Jobs
a|
List all jobs and their status.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action jobStatus
--verbose
----

a|
Policy
a|
Add a new local policy.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyAdd
--schedId 1
--backupTypeId 1
--policyType local
--policyName testPolicy
--primaryCount 7
--primaryAge 0
--verbose
----

a|
Policy (contd...)
a|
Add a new SnapMirror policy.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyAdd
--schedId 1
--backupTypeId 1
--policyType snapmirror
--policyName testPolicy
--primaryCount 7
--primaryAge 0
--verbose
----

a|
Add a new SnapVault policy.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyAdd
--schedId 1
--backupTypeId 1
--policyType snapvault
--policyName testPolicy
--primaryCount 7
--primaryAge 0
--secondaryCount 30
--secondaryAge 0
--verbose
----

a|
Update a SnapMirror policy.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyUpdate
--policyId 1
--schedId 1
--backupTypeId 1
--policyType snapmirror
--policyName testPolicy
--primaryCount 7
--primaryAge 0
--verbose
----

a|
Policy (contd...)
a|
Update a SnapVault policy.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyUpdate
--policyId 1
--schedId 1
--backupTypeId 1
--policyType snapvault
--policyName testPolicy
--primaryCount 7
--primaryAge 0
--secondaryCount 30
--secondaryAge 0
--verbose
----

a|
Delete a policy.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyDelete
--policyId 1
--verbose
----

a|
List all policies.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyList
--verbose
----

a|
Show additional details for a particular policy.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyDetails
--policyId 1
--verbose
----

a|
Assign policies to a profile.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action policyAssignToProfile
--policies testPolicy
--verbose
----

a|
Policy (contd...)
a|
Undo the assignment of policies for a profile.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action policyUnassignFromProfile
--verbose
----

a|
List all policies assigned to a profile.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action policyListForProfile
--verbose
----

a|
Policy schedules
a|
Create an hourly policy schedule.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedAdd
--schedName HourlyBackup
--schedFreqId 2
--schedActionId 1
--schedMin minute
--schedActive true
--verbose
----

a|
Create a daily policy schedule.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedAdd
--schedName DailyBackup
--schedFreqId 3
--schedActionId 1
--schedHour hour
--schedMin minute
--schedActive true
--verbose
----

a|
Policy schedules (contd...)
a|
Create a weekly policy schedule.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedAdd
--schedName WeeklyBackup
--schedFreqId 4
--schedActionId 1
--schedDayOfWeek day_of_week
--schedHour hour
--schedMin minute
--schedActive true
--verbose
----

a|
Create a cron policy schedule.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedAdd
--schedName CronBackup
--schedFreqId 5
--schedActionId 1
--schedCron '0 0/5 14,18 * * ?'
--schedActive true
--verbose
----

a|
Update an hourly policy schedule.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedUpdate
--schedId 1
--schedName HourlyBackup
--schedFreqId 2
--schedActionId 1
--schedMin minute
--schedActive true
--verbose
----

a|
Policy schedules (contd...)
a|
Update a daily policy schedule.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedUpdate
--schedId 1
--schedName DailyBackup
--schedFreqId 3
--schedActionId 1
--schedHour hour
--schedMin minute
--schedActive true
--verbose
----

a|
Update a weekly policy schedule.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedUpdate
--schedId 1
--schedName WeeklyBackup
--schedFreqId 4
--schedActionId 1
--schedDayOfWeek day_of_week
--schedHour hour
--schedMin minute
--schedActive true
--verbose
----

a|
Update a cron policy schedule.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedUpdate
--schedId 1
--schedName CronBackup
--schedFreqId 5
--schedActionId 1
--schedCron '0 0/5 14,18 * * ?'
--schedActive true
--verbose
----

a|
Policy schedules (contd...)
a|
Delete a policy schedule.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedDelete
--schedId 1
--verbose
----

a|
List policy schedules.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedList
--verbose
----

a|
Show additional information about a policy schedule.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedDetails
--schedId 1
--verbose
----

a|
Profiles
a|
Create a new profile.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action profileCreate
--verbose
----

a|
Delete a profile.*Note:* The configuration files in the profile are also deleted.

a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action profileDelete
--verbose
----

a|
Restore
a|
Perform interactive restore.Performs an interactive file restore operation or an interactive volume restore operation for a given policy.

a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action restore
--policy Policy
--verbose
----

a|
Perform non-interactive volume restore.Performs a non-interactive volume restore.

a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action restore
--policy Policy
--verbose
--nonInteractive
--cntName controller
--volName volume
--backupName name
----

a|
Perform non-interactive file restore.Performs a non-interactive file restore.

a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action restore
--policy Policy
--verbose
--nonInteractive
--cntName controller
--volName volume
--backupName name
--files file_path1,file_path2,etc.
----

a|
Schedules
a|
Create a new hourly schedule.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedCreate
--policy Policy
--schedName HourlyBackup
--schedFreqId 2
--schedActionId 1
--schedMin minute
--schedActive true
--schedStartDate date
--verbose
----

a|
Create a new daily schedule.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedCreate
--policy Policy
--schedName DailyBackup
--schedFreqId 3
--schedActionId 1
--schedHour hour
--schedMin minute
--schedActive true
--schedStartDate date
--verbose
----

a|
Create a new weekly schedule.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedCreate
--policy Policy
--schedName WeeklyBackup
--schedFreqId 4
--schedActionId 1
--schedDayOfWeek day_of_week
--schedHour hour
--schedMin minute
--schedActive true
--schedStartDate date
--verbose
----

a|
Schedules (contd...)
a|
Create a new cron schedule.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedCreate
--policy Policy
--schedName CronBackup
--schedFreqId 5
--schedActionId 1
--schedCron "0 0/5 14,18 * * ?"
--schedActive true
--schedStartDate date
--verbose
----

a|
Run a schedule.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action schedRun
--schedId 1
--verbose
----

a|
Delete a schedule.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action schedDelete
--schedId 10
--verbose
----

a|
Update an hourly schedule.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedUpdate
--policy Policy
--schedName HourlyBackup
--schedFreqId 2
--schedId 1
--schedActionId 1
--schedMin minute
--schedActive true
--schedStartDate date
--verbose
----

a|
Schedules (contd...)
a|
Update a daily schedule.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedUpdate
--policy Policy
--schedName DailyBackup
--schedFreqId 3
--schedId 1
--schedActionId 1
--schedHour hour
--schedMin minute
--schedActive true
--schedStartDate date
--verbose
----

a|
Update a weekly schedule.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedUpdate
--policy Policy
--schedName WeeklyBackup
--schedFreqId 4
--schedId 1
--schedActionId 1
--schedDayOfWeek day_of_week
--schedHour hour
--schedMin minute
--schedActive true
--schedStartDate date
--verbose
----

a|
Update a cron schedule.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedUpdate
--policy Policy
--schedName CronBackup
--schedFreqId 5
--schedId 1
--schedActionId 1
--schedCron "0 0/5 14,18 * * ?"
--schedActive true
--schedStartDate date
--verbose
----

a|
Schedules (contd...)
a|
List all schedules.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action schedList
--verbose
----

a|
List supported scheduler actions.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action schedActionList
--verbose
----

a|
List supported scheduler frequencies.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action schedFreqList
--verbose
----

a|
Show additional details for a schedule ID.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action schedDetails
--schedId 1
--verbose
----

a|
scdump
a|
Create an scdump file.Dumps logs, configuration files, and support information about a particular profile in a .zip file called scdump located under the Snap Creator root directory.

a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
-- profile Profile
--config Config
--action scdump
--policy Policy
--verbose
----

a|
Snap Creator Server and Agent
a|
List the status for all agents known to the Snap Creator Server.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action agentStatus
--verbose
----

a|
Snap Creator Server and Agent (contd...)
a|
Ping a Snap Creator Server.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action pingServer
--verbose
----

a|
Ping a Snap Creator Agent.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action pingAgent
--agentName host_name
--agentPort port
--verbose
----

a|
Archive
a|
Perform archive log management according to the settings in the configuration file. This operation requires Snap Creator Agent.

a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action arch
--verbose
----

a|
Data protection capability
a|
Configure the NetApp Management Console data protection capability dataset for a given configuration.
a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action pmsetup
--verbose
----

a|
Show the data protection status of the SnapVault and SnapMirror relationship for a controller. If SnapVault or SnapMirror is not configured, the results are not displayed.

a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action dpstatus
--verbose
----

a|
Quiesce/unquiesce
a|
Perform the quiesce operation for a given application. This operation requires Snap Creator Agent.

a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action quiesce
--verbose
----

a|
Perform the unquiesce operation for a given application. This operation requires Snap Creator Agent.

a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action unquiesce
--verbose
----

a|
Discover
a|
Perform discovery for a given application. This operation requires Snap Creator Agent.

a|

----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action discover
--verbose
----

|===
