---
permalink: administration/reference_post_commands.html
sidebar: sidebar
keywords: 
summary: 'Snap Creator Server includes several configuration file POST commands.'
---
= POST commands
:icons: font
:imagesdir: ../media/

[.lead]
Snap Creator Server includes several configuration file POST commands.

|===
| Command| Description
a|
POST_APP_ QUIESCECMD ##
a|
This is a post-application backup start command, where ## is a number from 01-99.
a|
POST_NTAP_CMD ##
a|
This is a post command, where ## is a number from 01-99. This runs after all operations are complete.
a|
POST_APP_UNQUIESCE _CMD ##
a|
This is a post-application backup stop command, where ## is a number from 01-99.
a|
POST_NTAP_DATA_ TRANSFER_CMD ##
a|
This is a post-data transfer command that runs after a SnapVault or SnapMirror transfer, where ## is a number from 01-99.
a|
POST_RESTORE_ CMD ##
a|
This is an optional command that can be run after you complete an interactive restore. It enables you to interact with the application being restored. After your restore is complete, you might want to start the application. *Note:* This is not supported with the MySQL plug-in.

a|
POST_CLONE_CREATE_ CMD ##
a|
This is an optional command that can be run after ONTAPI cloning operations occur, where ## is a number from 01-99. The commands are used to perform operations such as mounting cloned file systems.
|===
