---
permalink: administration/task_customizing_the_default_keystore.html
sidebar: sidebar
keywords: keystore, certificate, keytool, windows, unix
summary: 'You can customize the default keystore or certificate by using the keytool command that is available on Windows and UNIX.'
---
= Customizing the default keystore
:icons: font
:imagesdir: ../media/

[.lead]
You can customize the default keystore or certificate by using the keytool command that is available on Windows and UNIX.

The keytool command is provided by Java. In some environments, you might have to switch to the Java installation directory in order to run the keytool command.

Snap Creator does not support truststores.

. Stop the Snap Creator Agent.
. Generate a new keystore with a single certificate:
+
`keytool -genkeypair -alias alias_name -keystore keystore_file -keypass private_key_password -storepass keystore_password`
+
keytool -genkeypair -alias servicekey -keystore serviceKeystore.jks -keypass kypswd123 -storepass kystrpswd123

. Copy the keystore file to the scAgent4.3.0/etc/ directory.
. Update the KEYSTORE_FILE=keystore_file and KEYSTORE_PASS=keystore password parameters in the Snap Creator Agent configuration file (scAgent4.3.0/etc/allowed_commands.config).
. Start the Snap Creator Agent.

*Related information*

xref:task_starting_verifying_and_stopping_the_snap_creator_agent_on_windows.adoc[Starting, verifying, and stopping Snap Creator Agent on Windows]

xref:task_starting_verifying_and_stopping_the_snap_creator_agent_on_unix.adoc[Starting, verifying, and stopping Snap Creator Agent on UNIX]
