---
permalink: administration/task_setting_snap_creator_server_credentials.html
sidebar: sidebar
keywords: snap, creator, server, credentials, scadmin, port
summary: 'You can store the Snap Creator Server credentials (such as server host name or IP address, port, user, and password settings) to avoid entering the credentials on the command-line interface (CLI) multiple times. When required, you can remove the stored credentials.'
---
= Setting Snap Creator Server credentials
:icons: font
:imagesdir: ../media/

[.lead]
You can store the Snap Creator Server credentials (such as server host name or IP address, port, user, and password settings) to avoid entering the credentials on the command-line interface (CLI) multiple times. When required, you can remove the stored credentials.

The procedure for setting the Snap Creator Server credentials is the same for Windows and UNIX. The following procedure uses examples from the UNIX environment.

. On the host where the Snap Creator Server is installed, enter the following command from the Snap Creator Server installation directory:
+
`/install_path/scServer4.3/snapcreator --credentials`
+
The following output is displayed, enabling you to set the default credentials for the Snap Creator Server:
+
----
Enter user: SCadmin

Enter password:

Enter Snap Creator server hostname or IP [localhost]:
Enter Snap Creator server port [8443]:
Enter Profile name ( or * for any profile: *
Enter Config name ( or * for any config: *
----

. Enter the appropriate information for each entry.
+
After you enter your input for the Config name entry, the credentials are saved, and the following message is displayed: INFO: CLI credentials stored successfully. The credentials are stored in the snapcreator.credentials file in the .snapcreatordirectory or folder in the home directory.

. If you want to remove the stored credentials, delete the snapcreator.credentials file.
