---
permalink: installation/reference_cli_commands_for_creating_svm_roles.html
sidebar: sidebar
keywords: cli, commands, creating, svm, roles, role create
summary: 'The following table lists the commands that are required to create a role for a new SVM user.'
---
= CLI commands for creating SVM roles
:icons: font
:imagesdir: ../media/

[.lead]
The following table lists the commands that are required to create a role for a new SVM user.

[options="header"]
|===
| Command directory name| Command to be run
a|
adduser
a|
role create -role VSERVERRBACROLE_New -cmddirname "adduser" -vserver Snapcreator
a|
event generate-autosupport-log
a|
role create -role VSERVERRBACROLE_New -cmddirname "event generate-autosupport-log" -vserver Snapcreator
a|
lun comment
a|
role create -role VSERVERRBACROLE_New -cmddirname "lun comment" -vserver Snapcreator
a|
lun create
a|
role create -role VSERVERRBACROLE_New -cmddirname "lun create" -vserver Snapcreator
a|
lun delete
a|
role create -role VSERVERRBACROLE_New -cmddirname "lun delete" -vserver Snapcreator
a|
lun geometry
a|
role create -role VSERVERRBACROLE_New -cmddirname "lun geometry" -vserver Snapcreator
a|
lun igroup add
a|
role create -role VSERVERRBACROLE_New -cmddirname "lun igroup add" -vserver Snapcreator
a|
lun igroup create
a|
role create -role VSERVERRBACROLE_New -cmddirname "lun igroup create" -vserver Snapcreator
a|
lun igroup set
a|
role create -role VSERVERRBACROLE_New -cmddirname "lun igroup set" -vserver Snapcreator
a|
lun igroup show
a|
role create -role VSERVERRBACROLE_New -cmddirname "lun igroup show" -vserver Snapcreator
a|
lun map
a|
role create -role VSERVERRBACROLE_New -cmddirname "lun map" -vserver Snapcreator
a|
lun mapping show
a|
role create -role VSERVERRBACROLE_New -cmddirname "lun mapping show" -vserver Snapcreator
a|
lun modify
a|
role create -role VSERVERRBACROLE_New -cmddirname "lun modify" -vserver Snapcreator
a|
lun move
a|
role create -role VSERVERRBACROLE_New -cmddirname "lun move" -vserver Snapcreator
a|
lun offline
a|
role create -role VSERVERRBACROLE_New -cmddirname "lun offline" -vserver Snapcreator
a|
lun online
a|
role create -role VSERVERRBACROLE_New -cmddirname "lun online" -vserver Snapcreator
a|
lun resize
a|
role create -role VSERVERRBACROLE_New -cmddirname "lun resize"-vserver Snapcreator
a|
lun show
a|
role create -role VSERVERRBACROLE_New -cmddirname "lun show" -vserver Snapcreator
a|
lun unmap
a|
role create -role VSERVERRBACROLE_New -cmddirname "lun unmap" -vserver Snapcreator
a|
network
a|
role create -role VSERVERRBACROLE_New -cmddirname "network" -vserver SnapCreator
a|
network connections
a|
role create -role VSERVERRBACROLE_New -cmddirname "network connections" -vserver SnapCreator
a|
network connections active
a|
role create -role VSERVERRBACROLE_New -cmddirname "network connections active" -vserver SnapCreator
a|
network connections listening show
a|
role create -role VSERVERRBACROLE_New -cmddirname "network connections listening show" -vserver SnapCreator
a|
network interface
a|
role create -role VSERVERRBACROLE_New -cmddirname "network interface" -vserver SnapCreator
a|
network routing-groups
a|
role create -role VSERVERRBACROLE_New -cmddirname "network routing-groups" -vserver SnapCreator
a|
restore-file
a|
role create -role VSERVERRBACROLE_New -cmddirname "restore-file" -vserver Snapcreator
a|
snapmirror
a|
role create -role VSERVERRBACROLE_New -cmddirname "snapmirror" -vserver SnapCreator
a|
version
a|
role create -role VSERVERRBACROLE_New -cmddirname "version" -vserver Snapcreator
a|
volume
a|
role create -role VSERVERRBACROLE_New -cmddirname "volume"
a|
volume autosize
a|
role create -role VSERVERRBACROLE_New -cmddirname "volume autosize" -vserver Snapcreator
a|
volume clone
a|
role create -role VSERVERRBACROLE_New -cmddirname "volume clone" -vserver Snapcreator
a|
volume clone create
a|
role create -role VSERVERRBACROLE_New -cmddirname "volume clone create" -vserver Snapcreator
a|
volume create
a|
role create -role VSERVERRBACROLE_New -cmddirname "volume create" -vserver Snapcreator
a|
volume destroy
a|
role create -role VSERVERRBACROLE_New -cmddirname "volume destroy" -vserver Snapcreator
a|
volume efficiency off
a|
role create -role VSERVERRBACROLE_New -cmddirname "volume efficiency off" -vserver Snapcreator
a|
volume efficiency on
a|
role create -role VSERVERRBACROLE_New -cmddirname "volume efficiency on" -vserver Snapcreator
a|
volume efficiency start
a|
role create -role VSERVERRBACROLE_New -cmddirname "volume efficiency start" -vserver Snapcreator
a|
volume efficiency show
a|
role create -role VSERVERRBACROLE_New -cmddirname "volume efficiency show" -vserver Snapcreator
a|
volume file
a|
role create -role VSERVERRBACROLE_New -cmddirname "volume file" -vserver Snapcreator
a|
volume file clone
a|
role create -role VSERVERRBACROLE_New -cmddirname "volume file clone" -vserver Snapcreator
a|
volume file clone create
a|
role create -role VSERVERRBACROLE_New -cmddirname "volume file clone create" -vserver Snapcreator
a|
volume modify
a|
role create -role VSERVERRBACROLE_New -cmddirname "volume modify" -vserver Snapcreator
a|
volume mount
a|
role create -role VSERVERRBACROLE_New -cmddirname "volume mount" -vserver Snapcreator
a|
volume offline
a|
role create -role VSERVERRBACROLE_New -cmddirname "volume offline" -vserver Snapcreator
a|
volume show
a|
role create -role VSERVERRBACROLE_New -cmddirname "volume show" -vserver Snapcreator
a|
volume size
a|
role create -role VSERVERRBACROLE_New -cmddirname "volume size" -vserver Snapcreator
a|
volume snapshot create
a|
role create -role VSERVERRBACROLE_New -cmddirname "volume snapshot create" -vserver Snapcreator
a|
volume snapshot delete
a|
role create -role VSERVERRBACROLE_New -cmddirname "volume snapshot delete" -vserver Snapcreator
a|
volume snapshot restore
a|
role create -role VSERVERRBACROLE_New -cmddirname "volume snapshot restore" -vserver Snapcreator
a|
volume unmount
a|
role create -role VSERVERRBACROLE_New -cmddirname "volume unmount" -vserver Snapcreator
a|
vserver export-policy rule show
a|
role create -role VSERVERRBACROLE_New -cmddirname "vserver export-policy rule show" -vserver Snapcreator
a|
vserver export-policy show
a|
role create -role VSERVERRBACROLE_New -cmddirname "vserver export-policy show" -vserver Snapcreator
a|
vserver fcp
a|
role create -role VSERVERRBACROLE_New -cmddirname "vserver fcp" -vserver Snapcreator
a|
vserver fcp initiator show
a|
role create -role VSERVERRBACROLE_New -cmddirname "vserver fcp initiator show" -vserver Snapcreator
a|
vserver fcp show
a|
role create -role VSERVERRBACROLE_New -cmddirname "vserver fcp show" -vserver Snapcreator
a|
vserver fcp status
a|
role create -role VSERVERRBACROLE_New -cmddirname "vserver fcp status" -vserver Snapcreator
a|
vserver iscsi
a|
role create -role VSERVERRBACROLE_New -cmddirname "vserver iscsi" -vserver Snapcreator
a|
vserver iscsi connection show
a|
role create -role VSERVERRBACROLE_New -cmddirname "vserver iscsi connection show" -vserver Snapcreator
a|
vserver iscsi interface accesslist add
a|
role create -role VSERVERRBACROLE_New -cmddirname "vserver iscsi interface accesslist add" -vserver Snapcreator
a|
vserver iscsi interface accesslist show
a|
role create -role VSERVERRBACROLE_New -cmddirname "vserver iscsi interface accesslist show" -vserver Snapcreator
a|
vserver iscsi isns query
a|
role create -role VSERVERRBACROLE_New -cmddirname "vserver iscsi isns query" -vserver Snapcreator
a|
vserver iscsi nodename
a|
role create -role VSERVERRBACROLE_New -cmddirname "vserver iscsi nodename" -vserver Snapcreator
a|
vserver iscsi session show
a|
role create -role VSERVERRBACROLE_New -cmddirname "vserver iscsi session show" -vserver Snapcreator
a|
vserver iscsi show
a|
role create -role VSERVERRBACROLE_New -cmddirname "vserver iscsi show" -vserver Snapcreator
a|
vserver iscsi status
a|
role create -role VSERVERRBACROLE_New -cmddirname "vserver iscsi status" -vserver Snapcreator
a|
vserver nfs
a|
role create -role VSERVERRBACROLE_New -cmddirname "vserver nfs" -vserver Snapcreator
a|
vserver nfs status
a|
role create -role VSERVERRBACROLE_New -cmddirname "vserver nfs status" -vserver Snapcreator
a|
vserver services dns hosts show
a|
role create -role VSERVERRBACROLE_New -cmddirname "vserver services name-service dns hosts show" -vserver SnapCreator
a|
vserver services unix-group create
a|
role create -role VSERVERRBACROLE_New -cmddirname "vserver services name-service unix-group create" -vserver Snapcreator
a|
vserver services unix-group show
a|
role create -role VSERVERRBACROLE_New -cmddirname "vserver services name-service unix-group show" -vserver Snapcreator
a|
vserver services unix-user create
a|
role create -role VSERVERRBACROLE_New -cmddirname "vserver services name-service unix-user create" -vserver Snapcreator
a|
vserver services unix-user show
a|
role create -role VSERVERRBACROLE_New -cmddirname "vserver services name-service unix-user show" -vserver Snapcreator
|===
