---
permalink: installation/reference_cli_command_for_creating_cluster_roles.html
sidebar: sidebar
keywords: cli, commands, creating, cluster, roles, role create
summary: 'The following table lists the commands that are required to create a role for a new cluster user.'
---
= CLI commands for creating cluster roles
:icons: font
:imagesdir: ../media/

[.lead]
The following table lists the commands that are required to create a role for a new cluster user.

[options="header"]
|===
| Command directory name| Command to be run
a|
cluster identity show
a|
role create -role CRBAC_New -cmddirname "cluster identity show" -vserver clus3240rre
a|
event
a|
role create -role CRBAC_New -cmddirname "event" -vserver clus3240rre
a|
event config
a|
role create -role CRBAC_New -cmddirname "event config" -vserver clus3240rre
a|
event destination
a|
role create -role CRBAC_New -cmddirname "event destination" -vserver clus3240rre
a|
event log
a|
role create -role CRBAC_New -cmddirname "event log" -vserver clus3240rre
a|
event mailhistory
a|
role create -role CRBAC_New -cmddirname "event mailhistory" -vserver clus3240rre
a|
event route
a|
role create -role CRBAC_New -cmddirname "event route" -vserver clus3240rre
a|
event snmphistory
a|
role create -role CRBAC_New -cmddirname "event snmphistory" -vserver clus3240rre
a|
event status
a|
role create -role CRBAC_New -cmddirname "event status" -vserver clus3240rre
a|
lun comment
a|
role create -role CRBAC_New -cmddirname "lun comment" -vserver clus3240rre
a|
lun create
a|
role create -role CRBAC_New -cmddirname "lun create" -vserver clus3240rre
a|
lun delete
a|
role create -role CRBAC_New -cmddirname "lun delete" -vserver clus3240rre
a|
lun geometry
a|
role create -role CRBAC_New -cmddirname "lun geometry" -vserver clus3240rre
a|
lun igroup add
a|
role create -role CRBAC_New -cmddirname "lun igroup add" -vserver clus3240rre
a|
lun igroup create
a|
role create -role CRBAC_New -cmddirname "lun igroup create" -vserver clus3240rre
a|
lun igroup set
a|
role create -role CRBAC_New -cmddirname "lun igroup set" -vserver clus3240rre
a|
lun igroup show
a|
role create -role CRBAC_New -cmddirname "lun igroup show" -vserver clus3240rre
a|
lun map
a|
role create -role CRBAC_New -cmddirname "lun map" -vserver clus3240rre
a|
lun mapping show
a|
role create -role CRBAC_New -cmddirname "lun mapping show" -vserver clus3240rre
a|
lun modify
a|
role create -role CRBAC_New -cmddirname "lun modify" -vserver clus3240rre
a|
lun move
a|
role create -role CRBAC_New -cmddirname "lun move" -vserver clus3240rre
a|
lun offline
a|
role create -role CRBAC_New -cmddirname "lun offline" -vserver clus3240rre
a|
lun online
a|
role create -role CRBAC_New -cmddirname "lun online" -vserver clus3240rre
a|
lun resize
a|
role create -role CRBAC_New -cmddirname "lun resize" -vserver clus3240rre
a|
lun show
a|
role create -role CRBAC_New -cmddirname "lun show" -vserver clus3240rre
a|
lun unmap
a|
role create -role CRBAC_New -cmddirname "lun unmap" -vserver clus3240rre
a|
network
a|
role create -role CRBAC_New -cmddirname "network" -vserver clus3240rre
a|
network fcp adapter show
a|
role create -role CRBAC_New -cmddirname "network fcp adapter show" -vserver clus3240rre
a|
network interface show
a|
role create -role CRBAC_New -cmddirname "network interface show" -vserver clus3240rre
a|
security login role show
a|
role create -role CRBAC_New -cmddirname "security login role show" -vserver clus3240rre
a|
security login show
a|
role create -role CRBAC_New -cmddirname "security login show" -vserver clus3240rre
a|
snapmirror
a|
role create -role CRBAC_New -cmddirname "snapmirror" -vserver clus3240rre
a|
storage aggregate
a|
role create -role CRBAC_New -cmddirname "storage aggregate" -vserver clus3240rre
a|
system license show
a|
role create -role CRBAC_New -cmddirname "system license show" -vserver clus3240rre
a|
system node
a|
role create -role CRBAC_New -cmddirname "system node" -vserver clus3240rre
a|
system node autosupport
a|
role create -role CRBAC_New -cmddirname "system node autosupport" -vserver clus3240rre
a|
system node autosupport invoke
a|
role create -role CRBAC_New -cmddirname "system node autosupport invoke" -vserver clus3240rre
a|
system node show
a|
role create -role CRBAC_New -cmddirname "system node show" -vserver clus3240rre
a|
system node run
a|
role create -role CRBAC_New -cmddirname "system node run" -vserver clus3240rre
a|
system services ndmp
a|
role create -role CRBAC_New -cmddirname "system services ndmp" -vserver clus3240rre
a|
version
a|
role create -role CRBAC_New -cmddirname "version" -vserver clus3240rre
a|
version
a|
security login role create -role bainew1 -vserver SnapCreator -cmddirname "version" -access readonly
a|
vserver export-policy rule create
a|
role create -role CRBAC_New -cmddirname "vserver export-policy rule create" -vserver clus3240rre
a|
vserver export-policy rule show
a|
role create -role CRBAC_New -cmddirname "vserver export-policy rule show" -vserver clus3240rre
a|
vserver export-policy show
a|
role create -role CRBAC_New -cmddirname "vserver export-policy show" -vserver clus3240rre
a|
vserver fcp
a|
role create -role CRBAC_New -cmddirname "vserver fcp" -vserver Snapcreator -vserver clus3240rre
a|
vserver fcp initiator show
a|
role create -role CRBAC_New -cmddirname "vserver fcp initiator show" -vserver clus3240rre
a|
vserver fcp show
a|
role create -role CRBAC_New -cmddirname "vserver fcp show" -vserver clus3240rre
a|
vserver fcp status
a|
role create -role CRBAC_New -cmddirname "vserver fcp status" -vserver clus3240rre
a|
vserver iscsi connection show
a|
role create -role CRBAC_New -cmddirname "vserver iscsi connection show" -vserver clus3240rre
a|
vserver iscsi
a|
role create -role CRBAC_New -cmddirname "vserver iscsi" -vserver Snapcreator -vserver clus3240rre
a|
vserver iscsi interface accesslist add
a|
role create -role CRBAC_New -cmddirname "vserver iscsi interface accesslist add" -vserver clus3240rre
a|
vserver iscsi interface accesslist show
a|
role create -role CRBAC_New -cmddirname "vserver iscsi interface accesslist show" -vserver clus3240rre
a|
vserver iscsi nodename
a|
role create -role CRBAC_New -cmddirname "vserver iscsi nodename" -vserver clus3240rre
a|
vserver iscsi session show
a|
role create -role CRBAC_New -cmddirname "vserver iscsi session" show -vserver clus3240rre
a|
vserver iscsi show
a|
role create -role CRBAC_New -cmddirname "vserver iscsi show" -vserver clus3240rre
a|
vserver iscsi status
a|
role create -role CRBAC_New -cmddirname "vserver iscsi status" -vserver clus3240rre
a|
vserver nfs
a|
role create -role CRBAC_New -cmddirname "vserver nfs" -vserver Snapcreator -vserver clus3240rre
a|
vserver nfs status
a|
role create -role CRBAC_New -cmddirname "vserver nfs status" -vserver clus3240rre
a|
vserver options
a|
role create -role CRBAC_New -cmddirname "vserver options" -vserver clus3240rre
a|
vserver services unix-group create
a|
role create -role CRBAC_New -cmddirname "vserver services name-service unix-group create" -vserver clus3240rre
a|
vserver services unix-user create
a|
role create -role CRBAC_New -cmddirname "vserver services name-service unix-user create" -vserver clus3240rre
a|
vserver services unix-group show
a|
role create -role CRBAC_New -cmddirname "vserver services name-service unix-group show" -vserver clus3240rre
a|
vserver services unix-user show
a|
role create -role CRBAC_New -cmddirname "vserver services name-service unix-user show" -vserver clus3240rre
a|
vserver show
a|
role create -role CRBAC_New -cmddirname "vserver show" -vserver clus3240rre
a|
volume autosize
a|
role create -role CRBAC_New -cmddirname "volume autosize" -vserver clus3240rre
a|
volume clone create
a|
role create -role CRBAC_New -cmddirname "volume clone create" -vserver clus3240rre
a|
volume create
a|
role create -role CRBAC_New -cmddirname "volume create" -vserver clus3240rre
a|
volume destroy
a|
role create -role CRBAC_New -cmddirname "volume destroy" -vserver clus3240rre
a|
volume efficiency off
a|
role create -role CRBAC_New -cmddirname "volume efficiency off" -vserver clus3240rre
a|
volume efficiency on
a|
role create -role CRBAC_New -cmddirname "volume efficiency on" -vserver clus3240rre
a|
volume efficiency show
a|
role create -role CRBAC_New -cmddirname "volume efficiency show" -vserver clus3240rre
a|
volume efficiency start
a|
role create -role CRBAC_New -cmddirname "volume efficiency start" -vserver clus3240rre
a|
volume file
a|
role create -role CRBAC_New -cmddirname "volume file" -vserver clus3240rre
a|
volume file clone create
a|
role create -role CRBAC_New -cmddirname "volume file clone create" -vserver clus3240rre
a|
volume file show-disk-usage
a|
role create -role bainew1 -vserver SnapCreator -cmddirname "volume file show-disk-usage" -access all
a|
volume modify
a|
role create -role CRBAC_New -cmddirname "volume modify" -vserver clus3240rre
a|
volume offline
a|
role create -role CRBAC_New -cmddirname "volume offline" -vserver clus3240rre
a|
volume show
a|
role create -role CRBAC_New -cmddirname "volume show" -vserver clus3240rre
a|
volume size
a|
role create -role CRBAC_New -cmddirname "volume size" -vserver clus3240rre
a|
volume snapshot create
a|
role create -role CRBAC_New -cmddirname "volume snapshot create" -vserver clus3240rre
a|
volume unmount
a|
role create -role CRBAC_New -cmddirname "volume unmount" -vserver clus3240rre
|===
