---
permalink: installation/task_upgrading_the_snap_creator_agent_3_6_x_on_unix.html
sidebar: sidebar
keywords: upgrading, upgrade, snap, creator, agent, 3.6.x, unix
summary: 'You can upgrade directly from Snap Creator Agent 3.6.x on UNIX.'
---
= Upgrading the Snap Creator Agent 3.6.x on UNIX
:icons: font
:imagesdir: ../media/

[.lead]
You can upgrade directly from Snap Creator Agent 3.6.x on UNIX.

* You have stopped Snap Creator Agent before backing up the Snap Creator Agent directories to ensure that the backed up data is complete.
+
For example, enter the following command:
+
----
/install_path/scAgent3.6.x/bin/scAgent stop
----

* You have backed up the following directories, and all associated subdirectories and files, within the Snap Creator Agent directory (/install_path/scAgent3.6.x):
 ** agent.conf file (../config/agent.conf)
 ** Logs directory, if enabled (../logs)
 ** Plug-ins directory (../plugins)

The Snap Creator Agent in versions prior to 4.1 used a file named agent.conf to list commands outside of Snap Creator that could be executed on a Snap Creator Agent. In 4.1, the allowed_commands.config file is used.

Similarly, the agent.conf file listed hosts that the Snap Creator Agent was allowed to communicate with. By default, the Snap Creator Agent allowed communications with all Snap Creator Servers. However, if you chose to use this feature in previous versions of Snap Creator, the AUTHORIZED_HOSTS parameter in the agent.properties file now replaces that feature.

NOTE: If you did not use these parameters, a simple installation of the new agent is all that is required.

The paths provided in the following steps refer to the default installation path. The paths in the commands below might differ from those in your installation path.

. Stop Snap Creator Agent if you have not already done so.
+
For information, see the details provided earlier in this topic.

. Install the latest Snap Creator Agent, but do not start the Snap Creator Agent.
+
For details, see the information about installing Snap Creator Agent on UNIX.

. Open the backed up copy of the agent.conf file in a text editor.
+
The following is an example of agent.conf:
+
----
host: scServer@Lyon
command: rc_domino
----

. Open the new allowed_commands.config file (/install_path/scAgent4.1.x/etc/allowed_commands.config) in a text editor and copy the command line from agent.conf into the allowed_commands.config file; however, due to the enhanced security in the latest Snap Creator, make sure that the command is fully qualified.
+
From the previous example, the allowed_commands.config file should contain the following:
+
----
command: /etc/init.d/rc_domino
----
+
NOTE: If the command contains any spaces, then you must encapsulate the command within quotation marks.
+
You can add commands as needed, with each command on a separate line.
+
Save and close the file after making changes.

. Open the agent.properties file (/install_path/scAgent4.1.x/etc/agent.properties) in a text editor and change the default entry of AUTHORIZED_HOSTS=* to reflect the host setting in the agent.conf file, then save and close the file.
+
From the previous example, the AUTHORIZED_HOSTS parameter should contain the following:
+
----
AUTHORIZED_HOSTS=Lyon
----
+
Hosts can be added as needed, using commas to separate host names. Both host names and IP addresses are supported:
+
----
AUTHORIZED_HOSTS=Lyon, 10.10.10.192, Fuji01
----

. Start Snap Creator Agent by entering the following command:
+
----
/install_path/scAgent4.1.x/bin/scAgent start
----

*Related information*

xref:task_installing_the_snap_creator_agent_on_unix.adoc[Installing the Snap Creator Agent on UNIX-based systems]
