---
permalink: installation/task_installing_the_snap_creator_agent_on_unix.html
sidebar: sidebar
keywords: 
summary: 'The Snap Creator Agent runs on any open systems platform \(AIX, HP-UX, Linux, and Solaris\).'
---
= Installing the Snap Creator Agent on UNIX-based systems
:icons: font
:imagesdir: ../media/

[.lead]
The Snap Creator Agent runs on any open systems platform (AIX, HP-UX, Linux, and Solaris).

JRE 1.8 Update 72 or later must be installed. For details, see information in related links about installing Java on Snap Creator servers.

The person performing the installation must have sufficient access and privileges.

The default port for the Snap Creator Agent is 9090. Use netstat or a similar tool to verify that the network port (9090 or the port that you want to use) is available and is not already in use (for example, enter: `netstat -nap | grep 9090`).

Snap Creator should already be downloaded. For details, see information about downloading the Snap Creator software.

Linux is used here as the example platform.

. Copy the downloaded Snap Creator tar.gz file to the location where you want to install Snap Creator Agent.
+
NOTE: If you plan to use the IBM Domino plug-in, select a location other than the Domino data folder.

 .. To make a subdirectory, enter the following command with the directory name:
+
----
mkdir snap_creator_directory
----
+
----
mkdir /SC_41
----

 .. Copy the Snap Creator tar.gz file to the newly created directory by entering the following command:
+
----
cp NetApp_Snap_Creator_Frameworkrelease-os.tar.gz
/snap_creator_directory
----
+
----
cp NetApp_Snap_Creator_Framework4.1.0-Linux32.tar.gz
/SC_41
----

. Change to the directory to where the Snap Creator Framework .tar file is located and extract the file by entering the following commands:
+
NOTE: Depending on the UNIX environment, you might be required to unzip the file before entering the tar command.
+
----
cd snap_creator_directory
tar -xvf NetApp_Snap_Creator_Frameworkrelease-os.tar.gz
----

 ** snap_creator_directory is the location where Snap Creator will be installed.
 ** release is the current release of the Snap Creator software package.
 ** os is the operating system.
+
----
cd /sc_41
tar -xvf NetApp_Snap_Creator_Framework4.1.0-Linux32.tar.gz
----

+
This extracts both the Server and the Agent software. Typically, only the Snap Creator Server is configured. The agents normally reside on the database or application servers to be protected as seen in the following example:
+
----
NetApp_Snap_Creator_Framework4.1.0-Linux32.tar.gz  scServer4.1.0
scAgent4.1.0
----

. Enter the following commands and respond to the prompts shown in the example to set up the Snap Creator Agent.
+
----
cd scAgent*
./snapcreator --setup
Welcome to the NetApp Snap Creator Framework release-version!
\#\#\# Installation options \#\#\#
01. NetApp Snap Creator Framework release-version Agent
Select install option (enter a number or "q" to quit): <Enter 01>

END USER LICENSE AGREEMENT
<...the EULA displays...>

Do you accept the End User License Agreement (y|n): <Enter y>

Enter Snap Creator server port [9090]: <Enter agent port>

INFO: Updated NetApp Snap Creator Framework release-version
/install_path/scAgentrelease-version/engine/etc/agent.properties


INFO: To start scAgent please do the following:

/install_path/scAgentrelease-version/bin/scAgent start
----

. Start the Snap Creator Agent:
+
----
/install_path/scAgentrelease-version/bin/scAgent start
----
+
NOTE: To have the Snap Creator Agent run automatically at startup, add the start command to a script.
+
The steps to create a script differ slightly depending on the operating system used and the preferences of the system administrator managing the server. Generally, the start command for the Snap Creator Agent can be added to a file beginning with S9 (for example, S99scAgent) that is placed in the /path/to/rc2.d subdirectory. The rc2.d subdirectory is commonly located under /etc/, but this can depend on the host operating system and the particular configuration of the server. For more information, refer to the documentation of the operating system in use.
+
The following message appears:
+
----
Starting scAgent:
    Watchdog: Running
       Agent: Running
----

*Related information*

xref:task_installing_java_on_snap_creator_hosts.adoc[Installing Java on Snap Creator hosts]

xref:task_downloading_the_snap_creator_software.adoc[Downloading the Snap Creator software]
