---
permalink: domino-ops/reference_references.html
sidebar: sidebar
keywords: 
summary: 'You can find more information about Snap Creator, including release-specific information, on the NetApp Support Site.'
---
= Where to go next
:icons: font
:imagesdir: ../media/

[.lead]
You can find more information about Snap Creator, including release-specific information, on the NetApp Support Site.

* https://library.netapp.com/ecm/ecm_get_file/ECMLP2397467[Snap Creator Framework 4.3 Installation Guide]
+
Describes how to install the Snap Creator Agent and Snap Creator Server. The Snap Creator Agent installation includes the IBM Domino plug-in.

* https://library.netapp.com/ecm/ecm_get_file/ECMLP2397466[Snap Creator Framework 4.3 Administration Guide]
+
Describes how to administer the Snap Creator Framework after installation is complete.

* https://library.netapp.com/ecm/ecm_get_file/ECMLP2397462[Snap Creator Framework 4.3 Release Notes]
+
Describes new features of, important cautions for, known problems with, and limitations of Snap Creator Framework 4.1.1.

* https://library.netapp.com/ecm/ecm_download_file/ECMP1506026[SnapDrive 7.1 for Windows Installation Guide]
+
Describes how to install SnapDrive for Windows.

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-clus-peer/home.html[ONTAP 9 Cluster Peering Express Guide]
+
Describes how to quickly configure peer relationships between clusters and Storage Virtual Machines (SVMs).

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-sm-ic-cg/home.html[ONTAP 9 Volume Disaster Recovery Preparation Express Guide]
+
Describes how to prepare a storage system for SnapMirror replication.

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-sm-ic-fr/home.html[ONTAP 9 Volume Disaster Recovery Express Guide]
+
Describes how to prepare a storage system for SnapMirror recovery.

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-buvault/home.html[ONTAP 9 Volume Backup Using SnapVault Express Guide]
+
Describes how to prepare a storage system for SnapVault replication.

* http://www.netapp.com/in/media/tr-3917.pdf[NetApp Technical Report 3917: Best Practices for Domino on NetApp]
+
Describes best practices for the IBM Domino plug-in.

* http://www.netapp.com/us/media/tr-3588.pdf[Technical Report 3588: Integrating Domino 8.5 for Windows 2008 with a NetApp Storage System]
+
Describes how to integrate IBM Domino 8.5 for Windows 2008 with a NetApp storage system.

* http://www.netapp.com/us/media/tr-3691.pdf[Technical Report 3691: Integrating IBM Domino 8.5 for Linux with a NetApp Storage System]
+
Describes how to integrate IBM Domino 8.0.2 for Linux with a NetApp storage system.

* http://www.netapp.com/us/media/tr-3723.pdf[Technical Report 3723: Deploying Domino 8.0.2 in an AIX and NetApp Environment Using NFS]
+
Describes how to integrate IBM Domino 8.0.2 for AIX with a NetApp storage system.

* http://community.netapp.com/t5/Snap-Creator-Framework-Discussions/bd-p/snap-creator-framework-discussions[Snap Creator Framework Discussions]
+
Enables you to connect with peers, ask questions, exchange ideas, find resources, and share Snap Creator best practices.

* http://www.youtube.com/SnapCreatorTV[NetApp Video: SnapCreatorTV]
+
Enables you to view videos that demonstrate key Snap Creator technologies.
