---
permalink: domino-ops/reference_storage_layout_requirements.html
sidebar: sidebar
keywords: domino, ibm, storage, layout, requirements,
summary: A typical IBM Domino environment has at least three Domino volumes, one each for Domino data, Domino transaction logs, and the plug-in changeinfo directory. Many sites also have volumes for Domino DAOS and for view rebuilds.
---
= Storage layout requirements
:icons: font
:imagesdir: ../media/

[.lead]
A typical IBM Domino environment has at least three Domino volumes, one each for Domino data, Domino transaction logs, and the plug-in changeinfo directory. Many sites also have volumes for Domino DAOS and for view rebuilds.

The IBM Domino plug-in uses the changeinfo directory for changes recorded during backup operations and for copies of transaction logs used in up-to-the-minute restore operations. It is a best practice to store the changeinfo directory on a separate volume, to avoid inadvertently overwriting the information and to make it easier to back up.

You may also find it useful to have separate volumes for Domino DAOS (if it is enabled) and for view rebuilds. When Domino rebuilds a view (for example, when a user opens a view whose index has been deleted or when updall --R is run), it may generate temporary files to sort the data for rapid view rebuilding.

By default, these temporary files are located in the system's temporary folder or in the Domino data folder. IBM recommends changing the location of the temporary files to a different drive to distribute disk I/O and to ensure adequate space to rebuild views. To change the temporary folder used for view rebuilds, add the View_Rebuild_Dir setting to the notes.ini file.

The following table shows the preferred volume layout:

[options="header"]
|===
| Volume| Contents| Notes
a|
Volume 1
a|
Domino data
a|
FC, SAS, or SSD drives preferred.
a|
Volume 2
a|
Domino transaction logs
a|
FC, SAS, or SSD drives preferred.
a|
Volume 3
a|
changeinfo
a|
Stores changes recorded during backup operations and copies of transaction logs for use in up-to-the-minute restore operations.
a|
Volume 4
a|
View rebuild
a|
Optional. Stores temp files created during index updates. Can use RAM disk. Add View_Rebuild_Dir setting to notes.ini file.
a|
Volume 5
a|
DAOS repository
a|
Optional. Contains .dlo files from DAOS. Low I/O requirements make this a good candidate for SATA drives.
|===
NOTE: In virtual environments, guest-mounted disks are preferred.
