---
permalink: domino-ops/reference_references.html
sidebar: sidebar
keywords: domino, ibm, more, information, snap creator
summary: You can find more information about Snap Creator, including release-specific information, on the NetApp Support Site.
---
= Where to go next
:icons: font
:imagesdir: ../media/

[.lead]
You can find more information about Snap Creator, including release-specific information, on the NetApp Support Site.

* https://docs.netapp.com/us-en/snap-creator-framework/installation/index.html[Snap Creator Framework 4.3.3 Installation Guide]
+
Describes how to install the Snap Creator Agent and Snap Creator Server. The Snap Creator Agent installation includes the IBM Domino plug-in.

* https://docs.netapp.com/us-en/snap-creator-framework/administration/index.html[Snap Creator Framework 4.3.3 Administration Guide]
+
Describes how to administer the Snap Creator Framework after installation is complete.

* https://docs.netapp.com/us-en/snap-creator-framework/releasenotes.html[Snap Creator Framework 4.3 Release Notes]
+
Describes new features of, important cautions for, known problems with, and limitations of Snap Creator Framework 4.1.1.

* https://library.netapp.com/ecm/ecm_download_file/ECMP1506026[SnapDrive 7.1 for Windows Installation Guide]
+
Describes how to install SnapDrive for Windows.

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-clus-peer/home.html[ONTAP 9 Cluster Peering Express Guide]
+
Describes how to quickly configure peer relationships between clusters and Storage Virtual Machines (SVMs).

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-sm-ic-cg/home.html[ONTAP 9 Volume Disaster Recovery Preparation Express Guide]
+
Describes how to prepare a storage system for SnapMirror replication.

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-sm-ic-fr/home.html[ONTAP 9 Volume Disaster Recovery Express Guide]
+
Describes how to prepare a storage system for SnapMirror recovery.

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-buvault/home.html[ONTAP 9 Volume Backup Using SnapVault Express Guide]
+
Describes how to prepare a storage system for SnapVault replication.

* http://www.netapp.com/in/media/tr-3917.pdf[NetApp Technical Report 3917: Best Practices for Domino on NetApp]
+
Describes best practices for the IBM Domino plug-in.

* http://community.netapp.com/t5/Snap-Creator-Framework-Discussions/bd-p/snap-creator-framework-discussions[Snap Creator Framework Discussions]
+
Enables you to connect with peers, ask questions, exchange ideas, find resources, and share Snap Creator best practices.

* http://www.youtube.com/SnapCreatorTV[NetApp Video: SnapCreatorTV]
+
Enables you to view videos that demonstrate key Snap Creator technologies.
