---
permalink: domino-ops/task_configuring_snap_creator_to_use_snapdrive_by_using_the_gui.html
sidebar: sidebar
keywords: domino, ibm, adding, supplemental, commands
summary: You can add supplemental commands to your configuration after you create the configuration file. You can run the commands on the Snap Creator Server or Agent.
---
= Adding supplemental commands to the configuration
:icons: font
:imagesdir: ../media/

[.lead]
You can add supplemental commands to your configuration after you create the configuration file. You can run the commands on the Snap Creator Server or Agent.

To run a supplemental command on the Agent, you should already have added the command to the allowed_commands.config file on the Agent.

By default, supplemental commands run on the Agent. You can run a supplemental command on the Server by prepending the command with the text SERVER, followed by a colon (:). For example, SERVER:C:\myscript.bat. There is no requirement to allow the command on the Server.

You can use either the Snap Creator GUI or the Snap Creator CLI to add commands to your backup and restore configuration.

NOTE: This guide shows how to use the GUI to add commands. For information on how to use the CLI, see the https://library.netapp.com/ecm/ecm_download_file/ECMP12395422[Snap Creator Framework 4.1.2 Administration Guide].

. In the Profiles and Configurations pane, select the configuration file and click the *Commands* tab.
+
The following command types are available:
+
[options="header"]
|===
| Command type| Description
a|
Application Quiesce
a|
For non-plug-in use only. Ignore this command type.
a|
Application Un-Quiesce
a|
For non-plug-in use only. Ignore this command type.
a|
Pre Exit
a|
Use this type to run commands that tell Snap Creator what to do after a fatal error.
a|
Snapshot Copy Create
a|
Use this type to run your own Snapshot copy create commands.
|===
NOTE: Only a subset of the supported commands are available in the GUI. For information on the APP, ARCHIVE, MOUNT/UNMOUNT, and POST commands, see the link:https://library.netapp.com/ecm/ecm_download_file/ECMP12395422[Snap Creator Framework 4.1.2 Administration Guide].

. On the *Commands* tab, scroll to the section for the command type you want to use and click *Add*.
. Type over the text *Add Command Here* to enter the command.
+
To use SnapDrive for Windows to create a backup, you might enter the following in the section for the Snapshot Copy Create command type:
+
----
"C:\Program Files\NetApp\SnapDrive\sdcli.exe" snap create -s %SNAME-%SNAP_TYPE_%SNAP_TIME -D F G H
----
+
where:

 ** "C:\Program Files\NetApp\SnapDrive\sdcli.exe" is the default installation path for the SnapDrive CLI.
 ** %SNAME-%SNAP_TYPE_%SNAP_TIME specifies that the Snapshot copy name be formed from the configuration file name, the Snapshot policy (hourly, daily, or monthly), and the time and date the Snapshot copy was created.
 ** D is the switch and F G H are the mount points for the data to be backed up.
TIP: To run the command on the Server, prepend the command with the text SERVER, followed by a colon (:).

. When you are satisfied with your entry, press *Enter*.
. Repeat steps <<STEP_3F9C83DD05D84075AD0277213FD67C56,#STEP_3F9C83DD05D84075AD0277213FD67C56>> through <<STEP_FBEDD7AE105F42138EB35315EA9FA7CC,#STEP_FBEDD7AE105F42138EB35315EA9FA7CC>> to add another command.
. Click *Save* in the Configuration Content pane to save your changes.
